// Artifact renderers — faithful TS port of services/artifacts.py
// Markdown + CSV rendering from validated objects. ZIP is built client-side.

import type {
  CoverageReport,
  PlaywrightBundle,
  RequirementAnalysis,
  RunSummary,
  TestCaseSuite,
  TestPlan,
} from "./models";
import { requirementCoveragePct, automationPct } from "./models";

const GENERATED_NOTE =
  "> Generated by Jira QA Crew. Every item traces to Jira content; anything marked INFERRED or ASSUMPTION_REQUIRING_CONFIRMATION needs human review before it is treated as fact.";

function cell(text: string): string {
  return String(text ?? "").replace(/\|/g, "\\|");
}

function mdTable(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(" | ")} |`;
  const sep = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((r) => `| ${r.map(cell).join(" | ")} |`).join("\n");
  return [head, sep, body].join("\n");
}

export function renderRequirementsMd(a: RequirementAnalysis): string {
  const lines = [
    `# Requirements Analysis — ${a.ticket_key}`,
    "",
    GENERATED_NOTE,
    "",
    `**Summary:** ${a.summary}`,
    "",
    mdTable(
      ["Field", "Value"],
      [
        ["Issue type", a.issue_type || "not set"],
        ["Status", a.status || "not set"],
        ["Priority", a.priority || "not set"],
        ["Labels", a.labels.join(", ") || "none"],
        ["Components", a.components.join(", ") || "none"],
        ["Parent", a.parent || "none"],
        ["Subtasks", a.subtasks.join(", ") || "none"],
        ["Linked issues", a.linked_issues.join(", ") || "none"],
      ]
    ),
    "",
    "## Description Summary",
    "",
    a.description_summary || "_none_",
    "",
    "## Requirements",
    "",
  ];
  if (a.requirements.length) {
    lines.push(
      mdTable(
        ["ID", "Requirement", "Category", "Provenance", "Source quote"],
        a.requirements.map((r) => [r.id, r.text, r.category, r.provenance, r.source_quote || "—"])
      )
    );
  } else {
    lines.push("_No requirements were extracted._");
  }
  lines.push("", "## Acceptance Criteria", "");
  if (a.acceptance_criteria.length) {
    lines.push(
      mdTable(
        ["ID", "Criterion", "Verifies", "Provenance"],
        a.acceptance_criteria.map((c) => [c.id, c.text, c.requirement_ids.join(", "), c.provenance])
      )
    );
  } else {
    lines.push("_The ticket states no acceptance criteria._");
  }
  for (const [title, values] of [
    ["Business Rules", a.business_rules],
    ["Non-Functional Requirements", a.non_functional_requirements],
    ["Dependencies", a.dependencies],
    ["Constraints", a.constraints],
    ["Risks", a.risks],
    ["Assumptions", a.assumptions],
    ["Missing Information", a.missing_information],
    ["Open Questions", a.open_questions],
  ] as const) {
    if (values.length) {
      lines.push("", `## ${title}`, "", ...values.map((v) => `- ${v}`));
    }
  }
  return lines.join("\n");
}

export function renderTestPlanMd(plan: TestPlan): string {
  const lines = [`# Test Plan — ${plan.ticket_key}`, "", GENERATED_NOTE, "", `## ${plan.title}`, ""];
  for (const section of plan.sections) {
    lines.push(`## ${section.number}. ${section.title}`, "", section.content, "");
  }
  if (plan.scenarios.length) {
    lines.push("## High-Level Scenarios", "");
    lines.push(
      mdTable(
        ["ID", "Scenario", "Priority", "Traces to"],
        plan.scenarios.map((s) => [
          s.id,
          s.title,
          s.priority,
          [...s.requirement_ids, ...s.acceptance_criteria_ids].join(", "),
        ])
      )
    );
  }
  return lines.join("\n");
}

export function renderTestCasesMd(suite: TestCaseSuite): string {
  const lines = [`# Test Cases — ${suite.ticket_key}`, "", GENERATED_NOTE, ""];
  for (const tc of suite.test_cases) {
    lines.push(`## ${tc.id} — ${tc.title}`, "");
    lines.push(mdTable(
      ["Field", "Value"],
      [
        ["Priority", tc.priority],
        ["Type", tc.test_type],
        ["Automation", tc.automation_candidate],
        ["Objective", tc.objective],
        ["Traces to", [...tc.requirement_ids, ...tc.acceptance_criteria_ids].join(", ")],
      ]
    ));
    if (tc.preconditions.length) lines.push("", "**Preconditions:**", ...tc.preconditions.map((p) => `- ${p}`));
    if (tc.test_data.length) lines.push("", "**Test data:**", ...tc.test_data.map((d) => `- ${d}`));
    lines.push("", "| # | Action | Expected |", "| --- | --- | --- |");
    for (const step of tc.steps) {
      lines.push(`| ${step.number} | ${cell(step.action)} | ${cell(step.expected || "—")} |`);
    }
    lines.push("", `**Expected result:** ${tc.expected_result || "—"}`);
    if (tc.automation_rationale) lines.push("", `**Automation rationale:** ${tc.automation_rationale}`);
    if (tc.assumptions_or_blockers.length) {
      lines.push("", "**Assumptions / blockers:**", ...tc.assumptions_or_blockers.map((b) => `- ${b}`));
    }
    if (tc.tags.length) lines.push("", `**Tags:** ${tc.tags.join(", ")}`);
    lines.push("");
  }
  return lines.join("\n");
}

export function renderTestCasesCsv(suite: TestCaseSuite): string {
  const rows: string[][] = [["ID", "Title", "Priority", "Type", "Automation", "Requirements", "ACs", "Steps", "Expected result"]];
  for (const tc of suite.test_cases) {
    rows.push([
      tc.id, tc.title, tc.priority, tc.test_type, tc.automation_candidate,
      tc.requirement_ids.join(";"), tc.acceptance_criteria_ids.join(";"),
      String(tc.steps.length), tc.expected_result,
    ]);
  }
  return rows.map((r) => r.map(csvCell).join(",")).join("\n");
}

function csvCell(text: string): string {
  const s = String(text ?? "");
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function renderTraceabilityCsv(c: CoverageReport): string {
  const rows: string[][] = [["Requirement", "AC", "Test cases", "Automated", "Coverage", "Reason"]];
  for (const row of c.rows) {
    rows.push([
      row.requirement_id,
      row.acceptance_criterion_id || "—",
      row.test_case_ids.join("; ") || "—",
      row.automated_test_case_ids.join("; ") || "—",
      row.coverage_status,
      row.reason,
    ]);
  }
  return rows.map((r) => r.map(csvCell).join(",")).join("\n");
}

export function renderPlaywrightMd(bundle: PlaywrightBundle): string {
  const lines = [
    `# Playwright Automation — ${bundle.ticket_key}`,
    "",
    `**Readiness:** ${bundle.readiness}`,
    "",
  ];
  if (bundle.setup_notes) lines.push("## Setup", "", bundle.setup_notes, "");
  if (bundle.missing_information.length) {
    lines.push("## Required before execution", "", ...bundle.missing_information.map((m) => `- ${m}`), "");
  }
  if (bundle.assumptions.length) {
    lines.push("## Assumptions", "", ...bundle.assumptions.map((a) => `- ${a}`), "");
  }
  for (const file of bundle.files) {
    lines.push(`## ${file.path}`, "", "```typescript", file.content, "```", "");
  }
  if (bundle.traces.length) {
    lines.push("## Traces", "");
    lines.push(mdTable(
      ["Test", "Test case", "Traces to"],
      bundle.traces.map((t) => [
        t.test_name,
        t.test_case_id,
        [...t.requirement_ids, ...t.acceptance_criteria_ids].join(", "),
      ])
    ));
  }
  return lines.join("\n");
}

export function renderRunSummaryMd(run: RunSummary): string {
  const lines = [`# QA Run ${run.run_id}`, ""];
  for (const r of run.results) {
    const coverage = r.coverage
      ? `${requirementCoveragePct(r.coverage)}% req coverage, ${automationPct(r.coverage)}% automated`
      : "no coverage";
    lines.push(`- **${r.ticket_key}** — ${r.status} (${coverage})`);
    if (r.error) lines.push(`  error: ${r.error}`);
  }
  return lines.join("\n");
}
